### ISSUE TITLE
.NET Framework chrashes sometimes (if loot is dropping)

### ISSUE THREAD

**Issue by OrangutanKlaus1** [vmv/vmv-PoeHud#1]
When i kill the POEHud Task and restart it, it crashes again when my char is or enters the same area.
When i enter a new zone and restart the Task, everything is fine. I guess it has something to to with dropped loot. Sry... my english is not my native language but i guess you can understand what i mean. Framework is 4.6 

Debugg (only in german language):

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PoeHUD.Hud.Loot.PoeFilterVisitor.VisitMain(MainContext context)
   bei PoeFilterParser.Model.PoeFilterParser.MainContext.Accept[TResult](IParseTreeVisitor`1 visitor)
   bei Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   bei PoeHUD.Hud.Loot.ItemAlertPlugin.OnEntityAdded(EntityWrapper entity)
   bei System.Action`1.Invoke(T obj)
   bei PoeHUD.Models.EntityListWrapper.RefreshState()
   bei PoeHUD.Controllers.GameController.RefreshState()
   bei PoeHUD.Hud.ExternalOverlay.OnRender()
   bei PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   bei PoeHUD.Hud.UI.Graphics.RenderLoop()
   bei PoeHUD.Hud.ExternalOverlay.<OnLoad>b__14_0()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

**Comment by vmv** [comment]
Have you tried with the default filter provided from hud...thisBest.filter. Try that and see if it's ok, then we will see further.

**Comment by OrangutanKlaus1** [comment]
Yes, i deleted my POE-Folder 1 hour ago and downloaded the latest ZIP.

**Comment by OrangutanKlaus1** [comment]
okay.. i can reproduce this error now: After POEHud crashed, i killed the task and collected all new dropped items around me to my inventory. I restarted PoeHud and everything is fine. As soon as i drop down a Magic ilvl 79 Penetrating Arrow Quiver to the ground, POE crashes.
I try to figure out, if this will happen with other items too.

**Comment by OrangutanKlaus1** [comment]
After few more tests --> Monsters dropped another magic and later a white Penetrating Arrow Quiver --> POEHud crashed.

**Comment by vmv** [comment]
All this are happening when using the default filter ...or your own ?
Do you have anything in crafting_bases.txt ?
Check another filter.
Actually i will download another one and test myself...but i don't know if i have an Arrow Quiver.
I'll let you know how the results are.

**Comment by vmv** [comment]
Back after fast test...:
Using Atnee's .filter, i bought an  normal white Pen Arrow Quiver from vendor, and some other and got outside of the city...dropped them down..all normal, no errors.
Checked with both filters, the default one "thisBest.filter" & "Atnee's .filter"...no crash nor errors.
Can be something wrong with your filter, or something bad with the NetFramework 4.6...
Try reinstall first and see if works.

**Comment by OrangutanKlaus1** [comment]
Hi there,
i just restarted my PC and Windows 10 installed some updates (not Framwork...). Now everything is fine. Thank you and sorry for wasting your time.
