### ISSUE TITLE
2.1.2 with old item mod colours ?

### ISSUE THREAD

**Issue by OrangutanKlaus1** [vmv/vmv-PoeHud#14]
Hi VMV,

is there any chance that i can get a 2.1.2 Version but with the old item mod colours? You gave me the exe some Versions ago and i was really happy with it.
But only if it is not much affort for you.

Thank you !!
Greets

**Comment by vmv** [comment]
Ofc, if i have time i will build a version for you...just need again to remember what was what :DDDD

**Comment by OrangutanKlaus1** [comment]
Hi :)

we talked about some weeks ago in (now closed) issue #9. Perhaps you can read it and remember ?
If you can't remember i can give you more details :)

Thank you

**Comment by vmv** [comment]
Here it is : 
[vmv-PoeHud - Copy.zip](https://github.com/vmv/vmv-PoeHud/files/106663/vmv-PoeHud.-.Copy.zip)

**Comment by OrangutanKlaus1** [comment]
Thank you very much. This was really fast.

But: It is not like the exe you posted me some weeks ago. I don't need different colours for Prefix/Suffix (now white and gray). I need different colours for the T1-T19 or so description. Now "T2" and "T7" for example have the same gray colours on a item. 

I am drunk now and its hard for me to descripe what i mean. Cause english is not my native language.

I can give your more details tomorrow if you need.

Greetings

**Comment by vmv** [comment]
I have omitted a small change,....i think this is ok now :
[vmv-PoeHud - new.zip](https://github.com/vmv/vmv-PoeHud/files/106806/vmv-PoeHud.-.new.zip)

**Comment by OrangutanKlaus1** [comment]
Hi VMV,

thank you very much. Its okay now. But i am wondering, why for example 2x T4 on an item have different colours.

See Images here: http://imgur.com/a/kjdUF

Thx for your work

Greetings

**Comment by vmv** [comment]
Red color is the lowest possible value...while gradually the value increases...the color changes until top value.
