### ISSUE TITLE
PoeHud don't work after patch 2.1.0b

### ISSUE THREAD

**Issue by OrangutanKlaus1** [vmv/vmv-PoeHud#2]
Hi :)

After Patch 2.1.0b PoeHud don't work anymore. I can open Menü and configure all things, but they are not shown in overlay. Nothing changed on my site. Yesterday after 2.1.0 all was fine.

Thank you for your great work

**Comment by vmv** [comment]
We need new offsets, and right now i don't have them. Use F1 to use the Preload function until we get the new addresses...

**Comment by OrangutanKlaus1** [comment]
Thank you very much for the fast reply.

One last other question, nothing to do with this "issue", but dont know how to contact you elsewhere:
The new Item Tooltips/Item Mods are great, but the mod lines are now totaly white insted of showing me with colours (red green etc.) if the roll is good or not. Before i could see in 1 second, if i should pick up a crafting base white (implict good (green) or bad (red)). Or if the rolls of a rare / Unique are fine. Now its harder to see it.
Any chance to get this "mod range colours" back ?

Sry, my english is not the best, but i think you undertand what i mean.

Greets

**Comment by vmv** [comment]
Hmmm...was that used for this purpose, because if i remember correctly there were bad/low mods with the same color as good/higher mods.
There is an option now to choose your own color for tiers....like if it's T1, just put Red color there and instantly you will see it.
I can add that old method back of course or i can add 2 more tiers to be 5 in total,...
I don't think tiers 6+++ will be good for anyone :)

**Comment by OrangutanKlaus1** [comment]
Thx. I know about the Tier colours and its fine for me. I only meant the range colours of a tier mod (for example incr. Physical damage 142% (120% - 145%) on a weapon. The whole line is now only white. With PoeHud 0.3 and befor(?) the 142 was green or so and you could see that it is a high roll in its range in few secs.

Thx again for your great work.

**Comment by vmv** [comment]
Oh, i remember now, it's just a small change...don't worry, i will change it back and see how it goes...

**Comment by OrangutanKlaus1** [comment]
I can't wait for it :D. Thank you!

**Comment by j0hnbender** [comment]
offset changes in the works?

**Comment by vmv** [comment]
Nope, ...same as before, nothing changed. I'm waiting for TehCheat..maybe we can fix it.

**Comment by j0hnbender** [comment]
Awesome <3 and Thankyou
