### ISSUE TITLE
Question and dont know where to post it vmv

### ISSUE THREAD

**Issue by dopeshow** [vmv/vmv-PoeHud#3]
I got banned on the November wave. Was wondering if there was an updated info about it. My ban might of been my fault after i talked with my old guild on team speak later that day. I was new to PoE and had the hud since i started playing because i knew of turbo hud on D3 so figured there had to be one for poe.

Anyways when i got on team speak i said i got banned, soon as it came out of my mouth, one of the officers said because i used PoE hud. I never told anyone and it was before reddit or anything had post about ban wave of third party strongbox checker. They kicked me from team speak and so far haven't replied to my PM. Pretty safe to say one of them got GGG looking into me. why is below sorry for ramble. 

Only thing i can think of is being a noob, i might of got them looking at me when i would say things that wasn't on loot filters i guess and was hud but was to dumb to know it. Or magic pack over here, and im not in view of mobs.. Maybe little things, right before i got banned i did do my first few days of box/vaal zone spam. Just trying to be helpful maybe, it was my own fault. Got me thinking maybe it was like a ratio of instances to what boxes i opened or how often i spent in zones farming. Was always cautious about spamming zones but after 3 months thought i was safe, stupid on my part.

Didn't see how to private message on here but was wondering if both versions of your hud are stable or you been using them? As i don't want to lose my supporter packs or challenge rewards, is it safer to have a poe hud account. Then a clean one to buy stuff on and use mtx etc. Just wanting some imput from a longtime user. As Path isn't the same w/o poe hud lol. Get hella bored maybe that is wrong but rng is already a B. 

IF YOU READ ALL THAT, THANK YOU. If not i understand. Any input would be great, peace.

**Comment by vmv** [comment]
For now use the hud ONLY on a mule account and use it for farming. This is the best advise i can give you right now,...
I know that the game looks weird w/o the hud , but if you want to keep your main account safe, just use the hud on a separate one and make currency with it.
I never got banned but maybe this is just luck.
There is no safe version out yet, and i don't know when will be one.
Have fun,

**Comment by dopeshow** [comment]
Thanks for the reply. That is what i was thinking of doing. Would it be safer to have the main account like a guild leader. Make a few tabs to share gear so you dont have to trade will mule account. Just drop in guild stash or is it safer to invite to a party and just drop the gear on the ground when standing next to each other?

Any suggestions on where to start to learn about how get into learning how the hud works so one day i can maybe help out. If things cant be posted on here since its public. i can give my email. Just find it interesting and always wanting to learn about computer related thing s when they are tied to gaming.

**Comment by vmv** [comment]
I don't think they track the trades , as this game is based on trades. The thing with guild leader is also a good choice.
Just, don't abuse farming to catch their attention.
The hud is written in C# programming language...if you want to learn it ...:)

**Comment by dopeshow** [comment]
Ok thanks for the reply i didn't know how else to get in touch with you. I guess the issue can be close or w/e i know some don't like having it up. You say that like it's a headache on C#. Is that C++. i know that is a hashtag. Google said it means See sharp. Just so im clear on what is used.

**Comment by dopeshow** [comment]
I started using your hud is the blips on map that show regular/magic/rare etc mobs gone and the preload alerts. wasn't sure if they got turned off but setting didn't change anything. Maybe it was done as precaution of the ban wave?

**Comment by vmv** [comment]
No, it's just missing some offsets that i don't have and until someone provide them...the hud is practically not working. Use F1 if you want to see preloads. Press F1 twice and use that small graph.

**Comment by dopeshow** [comment]
Ah, how does one find the offsets, i assume its not easy or gotta come from someone on the inside? Not that it's a big deal but i dont see preloads like masters/strongbox etc no matter how many times i press F1. i checked and they are on. Maybe it different on H4VC version, use to use that a bunch. 

about the offsets thing, is it possible to make a VM with a alternate ip or mask. Then run a sniffer or dat miner. Never actually done them myself but use to play a mmo. You know the story probably or heard it before.A friend knew a "guy" who knew about that stuff, aka probably the friend and talked about stuff a bit but never revealed much. Because some accouts could sell for 4 to 5 digits so a bunch of hush hush stuff. Like i played years legit until i found out most of the top players had scripts/bots fishing for them all day so they always had tons of gold i never understood until it was almost common knowledge. 

Sorry for the ramble, maybe something in there worth a few cents

**Comment by vmv** [comment]
Using Ida Pro or Cheat Engine to find offsets, but to start now from scratch, heh, it's a big problem. The guys who got them in the past, i think they quit the game...and there is nobody who really knows how to get them. I don't know for sure....
I asked few people to help but they are busy or they do not play anymore.
H4vC master should work too with the same F1.

**Comment by dopeshow** [comment]
Oh im not using H4vC now, just your's. When i got banned i used both or if there was 3 maybe 3 at one time. Is the offset nothing more than the x and y to get the info on screen or is it more than that?

**Comment by dopeshow** [comment]
Trying to narrow down how i got banned and sticking to one version help a bit. Since there are already so many variables already not that i will ever know.

**Comment by vmv** [comment]
Offsets has changed for many things i assume, not only onScreen...
As you can see the hud is shown on the screen but the rest of the functions...have wrong addresses. All versions are using the same addresses btw...otherwise wouldn't work.
