### ISSUE TITLE
Item mod range colours? 

### ISSUE THREAD

**Issue by OrangutanKlaus1** [vmv/vmv-PoeHud#9]
Hi 😀

No real issue but don't know how to contact you elsewhere. 
What about the colours for the Item mod range colours we talked about some days ago? Do you plan to change it back as before? You said it's only a small effort. 

For memory:

"Thx. I know about the Tier colours and its fine for me. I only meant the range colours of a tier mod (for example incr. Physical damage 142% (120% - 145%) on a weapon. The whole line is now only white. With PoeHud 0.3 and befor(?) the 142 was green or so and you could see that it is a high roll in its range in few secs."

Thank you that everything else is working fine now again. 

Greetings

**Comment by thisTwo** [comment]
Hi, 
Eh, i forgot about that, let me look where the change up was...and i get back to you with a private version.
Nobody else asked for a change back actually. And with those problems with the offsets...completely forgot.

**Comment by vmv** [comment]
Hi, 
Eh, i forgot about that, let me look where the change up was...and i get back to you with a private version.
Nobody else asked for a change back actually. And with those problems with the offsets...completely forgot.

**Comment by vmv** [comment]
Here, see if it's what you need : http://www.mediafire.com/download/3rd928vgsqmtqr2/mod-vmv-PoeHud.zip

**Comment by OrangutanKlaus1** [comment]
Hey,

this is exactly what i meant. Thank you for this :)
It's a bit hard for me to explain cause english is not my native language.
It's not only the min-max rolls.... its also to see faster if you should or should not pick up a a high level crafting white ring / amu. If it is green --> pick it up. Otherewise not. If all only is white, you have to look twice and it disturbs my fast clearspeed ;). Another example are the rolls of unique items. With colours its faster to see if the roll is good or not etc.

Very great work. But one more wish: Is it possible to give fixed mods and implicits (without range) a other special colour ? At the moment bad rolls and fixed mods are all red. I remember the fixed ones had the current T1 colour (pink) some versions before.

See example pics: http://imgur.com/a/WFj6m

Thank you very much

**Comment by vmv** [comment]
Sure, here is the .exe for the old method of showing ItemMods, : http://www.mediafire.com/download/h5sdqxwrah2fxsm/old-PoeHUD.zip
Perhaps i will try to keep both methods, fi it's not hard to do it...:)

**Comment by OrangutanKlaus1** [comment]
Hi.. thank you. I will test it out
